# OpenSSF Scorecard Checks Workflow
#
# This workflow uses ossf/scorecard-action action to check repo based on
# OpenSSF Scorecard requirements / best practices
#
# Key Features:
# - Check the repo based on OpenSSF Scorecard requirements
# - Upload results into Security tab and OpenSSF
# - Scheduled daily scans
#
# Process Stages:
# 1. Scheduled Execution (Daily at 2 AM UTC)
# 2. Manual Execution
#
# Required Permissions:
# - id-token: write
# - security-events: write
#
# Note: Results are available in the Security tab and
# https://scorecard.dev/viewer/?uri=github.com/open-edge-platform/anomalib

name: Scorecards supply-chain security
on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  schedule:
    # Run security checks every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload the results to code-scanning dashboard
      id-token: write # Needed to publish results and get a badge

    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      # Upload the results to GitHub's code scanning dashboard
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: results.sarif
